apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  labels:
    app: sentinel
type: Opaque
data:
  # Base64 encoded value for "supersecretpassword"
  # echo -n "supersecretpassword" | base64
  redis-password: c3VwZXJzZWNyZXRwYXNzd29yZA==
